<?php
//$Id$

/**
 * See http://drupal.org/node/106716 for more information.
 */

/**
 * Implementation of hook_init().
 */
function product_price_alterer_field_init()
{
	drupal_add_css(drupal_get_path("module", "product_price_alterer_field") . "/product_price_alterer_field.css");
}

/**
 * Implementation of hook_field_info().
 */
function product_price_alterer_field_field_info()
{
	return array(
		"product_price_alterer" => array(
			"label" => t("Discounted Price"),
			"description" => t("Alters price for products where uc_discounts_alt discounts apply when added with a quantity of one or less"),
		),
	);
}

/**
 * Implementation of hook_content_is_empty().
 */
function product_price_alterer_field_content_is_empty($item, $field)
{
	return FALSE;
}

/**
 * Implementation of hook_widget_info().
 */
function product_price_alterer_field_widget_info()
{
	return array(
		"product_price_alterer" => array(
			"label" => "Default Display",
			"field types" => array("product_price_alterer"),
			"multiple values" => CONTENT_HANDLE_CORE,
			"callbacks" => array(
				"default value" => CONTENT_CALLBACK_DEFAULT,
			),
		),
	);
}

/**
 * Implementation of hook_widget().
 */
function product_price_alterer_field_widget(&$form, &$form_state, $field, $items, $delta = 0)
{
	$element = array(
		"#type" => $field["widget"]["type"],
		"#default_value" => isset($items[$delta]) ? $items[$delta] : NULL,
	);
	return $element;
}

/**
 * Implementation of hook_field_formatter_info().
 */
function product_price_alterer_field_field_formatter_info()
{
	return array(
		"default" => array(
			"label" => "Discount Description",
			"field types" => array("product_price_alterer"),
		),
	);
}

/**
 * Implementation of hook_field()
 */
function product_price_alterer_field_field($op, &$node, $field, &$items, $teaser, $page)
{
	switch ($op)
	{
		case "sanitize":
		case "view":
			//If items is empty, generate value by getting discounts that apply to this product
			if ( empty($items) )
			{
				//Determine discounts that apply to product when ordering a quantity of 1 or less
				$discounts = get_codeless_discounts_for_product_and_quantity($node, 1);
				if ( !empty($discounts) )
				{
					$item = array();
					$item["product_price_alterer"] = 
						theme("product_price_alterer_field_get_price_alterer_html_for_discounts", $node, $discounts);
					$items[] = $item;
				}
			}
			break;
	}
}

/**
 * Implementation of hook_theme().
 */
function product_price_alterer_field_theme()
{
	return array(
		"product_price_alterer_field_formatter_default" => array(
			"arguments" => array("element"),
		),
		"product_price_alterer_field_get_price_alterer_html_for_discounts" => array(
			"arguments" => array("product", "discounts"),
		),
	);
}

/**
 * Theme function for discounts product price alterer element.
 */
function theme_product_price_alterer_field_formatter_default($element)
{
	return $element["#item"]["product_price_alterer"];
}

/**
 * Theme function for producing dicounted price html and price altering javascript.
 */
function theme_product_price_alterer_field_get_price_alterer_html_for_discounts($product, $discounts)
{
	//Sum total discount and determine price with discounts
	$total_discount_amount = 0;
	foreach ($discounts as $discount)
		$total_discount_amount += $discount->amount;
	$discounted_price_with_discounts = $product->sell_price - $total_discount_amount;

	$sell_price_string = "<div><strike>" . t("Price:") . "&nbsp;" 
		. uc_currency_format($product->sell_price) . "</strike></div>";
	$discount_price_string = 
		"<div class='product-price-alterer-field-discounted-price'>" 
			. t("Discounted price:") . "&nbsp;" . uc_currency_format($discounted_price_with_discounts)
		. "</div>";

	//Alter price using javascript
	drupal_add_js( sprintf("$(document).ready(function()
		{
			$(\".sell-price:not(.product_price_alterer_field-processed):first\").each(function()
				{
					$(this).addClass(\"product_price_alterer_field-processed\")
						.addClass(\"product-price-alterer-field-sell-price\")
						.html(%s)
						.after( $(\".product-price-alterer-field-discounted-price:first\") );
				});
		});", drupal_to_js($sell_price_string) ), "inline");

	return $discount_price_string;
}
